name: "ethos_tokenization_pipeline"

data:
    path: "/home/joshua/data/mimic/mimic_iv/meds/mimic_iv_meds/MEDS_cohort/data"

save_path: "/home/joshua/data/nightingale/ehr_tokenisation/"

preprocessing:
    - type: "load_static_data"
      csv_filepath: "/home/joshua/data/mimic/mimic_iv/mimic_iv/3.1/hosp/admissions.csv"
      subject_id_column: "subject_id"
      columns:
        - column_name: "race"
          code_template: "DEMOGRAPHICS//RACE"
          valid_values: ["WHITE", "BLACK", "HISPANIC", "ASIAN", "OTHER"]
          mappings:
            "PORTUGUESE": "WHITE"
            "MULTIPLE RACE/ETHNICITY": "OTHER"
            "AMERICAN INDIAN/ALASKA NATIVE": "OTHER"
            "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER": "OTHER"
            "SOUTH AMERICAN": "HISPANIC"
          map_invalids_to: "RACE_UNKNOWN"
          value_prefix: "RACE//"
          insert_code: false
        - column_name: "marital_status"
          code_template: "DEMOGRAPHICS//MARITAL_STATUS"
          valid_values: ["SINGLE", "WIDOWED", "MARRIED", "DIVORCED"]
          map_invalids_to: "MARITAL_STATUS_UNKNOWN"
          value_prefix: "MARITAL_STATUS//"
          insert_code: false
    - type: "demographic_aggregation"
      measurements:
        - token_pattern: "BMI (kg/m2)"
          value_column: "text_value"
          aggregation: "median"
          num_bins: 10
          token_prefix: "BMI//"
          insert_code: false
          remove_original_tokens: true
    - type: "ethos_quantile_age"
      time_unit: "years"
      num_quantiles: 10
      prefix: "AGE_"
      insert_t1_code: false
      insert_t2_code: false
      keep_meds_birth: true

    - type: "quantile_bin"
      matching_type: "starts_with"
      matching_value: "LAB"
      value_column: "numeric_value"
      k: 10
    - type: "quantile_bin"
      matching_type: "starts_with"
      matching_value: "BMI"
      value_column: "text_value"
      k: 10
    - type: "quantile_bin"
      matching_type: "starts_with"
      matching_value: "Height"
      value_column: "text_value"
      k: 10
    - type: "quantile_bin"
      matching_type: "starts_with"
      matching_value: "Weight"
      value_column: "text_value"
      k: 10
    - type: "quantile_bin"
      matching_type: "starts_with"
      matching_value: "SUBJECT_FLUID_OUTPUT//Q//"
      value_column: "numeric_value"
      k: 10

postprocessing:
    - type: "demographic_sort_order"
      token_patterns:
        - "BMI//"           # BMI tokens appear first
        - "GENDER//"        # Gender tokens second
        - "MARITAL_STATUS//" # Marital tokens third  
        - "AGE_T"           # Age tokens fourth (matches both AGE_T1 and AGE_T2)
        - "RACE//"          # Race tokens last
        
    - type: "time_interval"
      interval_tokens:
        "5m-15m":
          min: 5
          max: 15
        "15m-45m":
          min: 15
          max: 45
        "45m-1h15m":
          min: 45
          max: 75
        "1h15m-2h":
          min: 75
          max: 120
        "2h-3h":
          min: 120
          max: 180
        "3h-5h":
          min: 180
          max: 300
        "5h-8h":
          min: 300
          max: 480
        "8h-12h":
          min: 480
          max: 720
        "12h-18h":
          min: 720
          max: 1080
        "18h-1d":
          min: 1080
          max: 1440
        "1d-2d":
          min: 1440
          max: 2880
        "2d-4d":
          min: 2880
          max: 5760
        "4d-7d":
          min: 5760
          max: 10080
        "7d-12d":
          min: 10080
          max: 17280
        "12d-20d":
          min: 17280
          max: 28800
        "20d-30d":
          min: 28800
          max: 43200
        "30d-2mt":
          min: 43200
          max: 86400
        "2mt-6mt":
          min: 86400
          max: 259200
        "6mt-":
          min: 259200
          
tokenization:
    tokenizer: "word_level"
    vocab_size: 5500
    insert_event_tokens: False
    insert_numeric_tokens: False
    insert_text_tokens: False