# Paths to the input data from your first pipeline
tokenized_data_dir: "/data/scratch/qc25022/liver/tokenised_data/train/"
vocab_file: "/data/scratch/qc25022/liver/tokenised_data/vocab.csv"

# Paths to your lookup tables for translation
medical_lookup_file: "/data/home/qc25022/cancer-extraction-pipeline/src/resources/MedicalDictTranslation.csv"
lab_lookup_file: "/data/home/qc25022/cancer-extraction-pipeline/src/resources/LabLookUP.csv"

# Path to your patient labels
labels_file: "/data/home/qc25022/cancer-extraction-pipeline/output/liver_study/subject_information.csv"

# Path for the final output file
output_txt_file: "/data/scratch/qc25022/liver/finetuning_dataset.txt"